---
- hosts: all
  become: true
  vars_prompt:
    - name: username
      prompt: Enter your dockerhub username
      private: false
    - name: password
      prompt: Enter your dockerhub password
  tasks:
    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
        state: latest
        update_cache: true
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true 
    - name: Install Docker CLI
      apt:
        name: docker-compose
        state: present
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true
    - name: Log into DockerHub
      docker_login:
        username: "{{username}}"
        password: "{{password}}"    
    - name: Pull nginx Docker image
      command: docker pull nginx
    - name: Run nginx Docker container
      docker_container:
        name: nginx-example-docker
        image: nginx
        state: started
        ports:
          - "443:80"